"""Turns an accepted candidate into a draft SDD intake artifact.

This is a hand-off point, not autonomous execution -- the draft primes a
human-supervised session to write a real spec; it never satisfies the SDD
spec phase's own exit gates itself.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from automation.store import Candidate

_NON_ALNUM = re.compile(r"[^a-z0-9]+")


def slugify(subject: str, message_id: str) -> str:
    slug = _NON_ALNUM.sub("-", subject.lower()).strip("-")
    return f"{slug[:40].strip('-')}-{message_id[:8]}"


def render_draft(candidate: Candidate, slug: str) -> str:
    return f"""# Draft intake: {candidate.subject}

> Generated by the automation pipeline's integrator from an accepted
> candidate. This is NOT a spec — it's source material for one. Run
> `agentalloy contract init --phase spec --slug {slug}` and write a real
> spec, using the material below as a starting point.

**Source**: {candidate.source}
**Received**: {candidate.received_at}
**Message ID**: {candidate.message_id}

## Why this was accepted

{candidate.rationale}

## Original content

{candidate.snippet}
"""
